// What the storage knows about a component type, which is as little as possible.
//
// A column holds raw bytes and has no type parameter — it cannot have one, since
// a generic class cannot be heap-allocated here and an archetype needs a run of
// columns of *different* types side by side. So the type travels as five plain
// numbers and function pointers, each one generated by a generic function at the
// site where `T` is still known. This is a hand-rolled vtable, and it is the
// same one a C++ type-erased container builds.
//
// ## Components are plain data
//
// Scalars, enums, `fvec3`, fixed arrays, and structs of those. **No `string`, no
// `T[]`, no classes.** That is a rule about content, not a limit of the
// mechanism: `init`, `copy` and `drop` below are written so an owning component
// would be correct, because writing them any other way would have been writing
// them wrongly on purpose. But nothing tests that case and nothing promises it,
// and a component with a heap allocation per entity is the thing an SoA layout
// exists to avoid. A component that wants a name holds an interned handle.
//
// The one place the rule is load-bearing rather than advisory is column growth:
// `column.ts` moves rows to a new buffer **bitwise**, which is right for plain
// data and for anything trivially relocatable, and wrong for a type whose
// constructor records its own address. Nothing in this language does that today.

/**
 * A component type, as the storage sees it.
 *
 * `size` of zero means a **tag** — an id an entity either has or has not, with
 * no data behind it — and an archetype gives one no column at all. That is not a
 * special case bolted on; it falls out of the size, which is what every loop
 * here is written against.
 */
export interface ComponentInfo {
    size: usize;
    align: usize;

    /**
     * Make `slot` hold a default `T`.
     *
     * Called on a slot whose bytes are already zero — a fresh column is zeroed
     * and so is every byte a growth adds — so this is a no-op for plain data.
     * It exists for the case where zero is not a valid `T`.
     */
    init: (slot: Pointer<unknown>) => void;

    /**
     * `destination = source`, by `T`'s own assignment.
     *
     * The destination must already hold a valid `T`, because assignment runs the
     * old value's destructor first. Every caller here satisfies that by having
     * initialised the slot; none of them writes into raw bytes.
     */
    copy: (destination: Pointer<unknown>, source: Pointer<unknown>) => void;

    /**
     * Destroy what `slot` holds and leave a default behind.
     *
     * A default rather than garbage, and that is the important half: the slot
     * stays a valid `T` afterwards, so the column's own teardown can run over
     * every slot without tracking which ones have been emptied.
     */
    drop: (slot: Pointer<unknown>) => void;
}

function initOf<T>(slot: Pointer<unknown>): void {
    slot.reify<T>()[0] = zeroed<T>();
}

function copyOf<T>(destination: Pointer<unknown>, source: Pointer<unknown>): void {
    destination.reify<T>()[0] = source.reify<T>()[0];
}

function dropOf<T>(slot: Pointer<unknown>): void {
    // `take` moves the value out and puts the default in, in one step, which is
    // exactly "destroy this and leave the slot valid". Written as a copy out and
    // a `zeroed<T>()` back it would be an allocation per drop for an owning `T`.
    const gone = take(slot.reify<T>()[0]);
}

function noInit(slot: Pointer<unknown>): void {}

function noCopy(destination: Pointer<unknown>, source: Pointer<unknown>): void {}

/**
 * The description of `T`.
 *
 *     const info = infoOf<Position>();
 *
 * Monomorphised at the call site, so the three function pointers are three real
 * functions specialised to `T` and each is a `memcpy` or nothing for plain data.
 */
export function infoOf<T>(): ComponentInfo {
    return {
        size: sizeOf<T>(),
        align: alignOf<T>(),
        init: initOf<T>,
        copy: copyOf<T>,
        drop: dropOf<T>,
    };
}

/**
 * A tag: an id with no data.
 *
 * Written out rather than `infoOf<SomeEmptyStruct>()`, because an empty struct
 * does not have size zero — a C layout gives it one byte so that two of them
 * have different addresses — and a column of one-byte nothings is a column that
 * did not need to exist.
 */
export function tagInfo(): ComponentInfo {
    return {size: 0, align: 1, init: noInit, copy: noCopy, drop: noInit};
}

/** Whether this id carries data, or is merely present. */
export function isTag(info: Reference<ComponentInfo>): boolean {
    return info.size === 0;
}
