// Generated by build.ts. Do not edit.
//
// One function per WGSL entry point. The resource counts are shadercc's own
// report, parsed back out of it, so they cannot drift from the shader — SDL
// takes these on trust and a wrong one samples zeroes with no error anywhere.

import { SDL_GPUShaderStage } from "../bindings/SDL3/index.ts";
import type { SDL_GPUComputePipeline, SDL_GPUDevice, SDL_GPUShader } from "../bindings/SDL3/index.ts";
import { loadComputePipeline, loadShader } from "./shader.ts";

/** `blur.wgsl` :: `blur_main` — compute, 8x8x1. */
export function blurBlurMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/blur.blur_main.spv",
        "blur_main",
        0, // samplers
        0, // read-only storage textures
        1, // read-only storage buffers
        0, // read-write storage textures
        1, // read-write storage buffers
        1, // uniform buffers
        8,
        8,
        1,
    );
}

/** `checker.wgsl` :: `generate` — compute, 8x8x1. */
export function checkerGenerate(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/checker.generate.spv",
        "generate",
        0, // samplers
        0, // read-only storage textures
        0, // read-only storage buffers
        1, // read-write storage textures
        0, // read-write storage buffers
        0, // uniform buffers
        8,
        8,
        1,
    );
}

/** `cluster_build.wgsl` :: `cs_main` — compute, 64x1x1. */
export function clusterBuildCsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/cluster_build.cs_main.spv",
        "cs_main",
        0, // samplers
        0, // read-only storage textures
        0, // read-only storage buffers
        0, // read-write storage textures
        1, // read-write storage buffers
        1, // uniform buffers
        64,
        1,
        1,
    );
}

/** `cluster_clear.wgsl` :: `cs_main` — compute, 64x1x1. */
export function clusterClearCsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/cluster_clear.cs_main.spv",
        "cs_main",
        0, // samplers
        0, // read-only storage textures
        0, // read-only storage buffers
        0, // read-write storage textures
        1, // read-write storage buffers
        0, // uniform buffers
        64,
        1,
        1,
    );
}

/** `cluster_cull.wgsl` :: `cs_main` — compute, 128x1x1. */
export function clusterCullCsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/cluster_cull.cs_main.spv",
        "cs_main",
        0, // samplers
        0, // read-only storage textures
        3, // read-only storage buffers
        0, // read-write storage textures
        2, // read-write storage buffers
        1, // uniform buffers
        128,
        1,
        1,
    );
}

/** `cluster_mark.wgsl` :: `cs_main` — compute, 8x8x1. */
export function clusterMarkCsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUComputePipeline> | null {
    return loadComputePipeline(
        device,
        "shaders/out/cluster_mark.cs_main.spv",
        "cs_main",
        1, // samplers
        0, // read-only storage textures
        0, // read-only storage buffers
        0, // read-write storage textures
        1, // read-write storage buffers
        1, // uniform buffers
        8,
        8,
        1,
    );
}

/** `depth_prepass.wgsl` :: `vs_main` — vertex. */
export function depthPrepassVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/depth_prepass.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        2, // uniform buffers
    );
}

/** `depth_prepass.wgsl` :: `fs_main` — fragment. */
export function depthPrepassFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/depth_prepass.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `forward.wgsl` :: `vs_main` — vertex. */
export function forwardVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/forward.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        2, // uniform buffers
    );
}

/** `forward.wgsl` :: `fs_main` — fragment. */
export function forwardFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/forward.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        3, // samplers
        0, // storage textures
        3, // storage buffers
        3, // uniform buffers
    );
}

/** `shadow_depth.wgsl` :: `vs_main` — vertex. */
export function shadowDepthVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/shadow_depth.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        1, // uniform buffers
    );
}

/** `shadow_depth.wgsl` :: `fs_main` — fragment. */
export function shadowDepthFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/shadow_depth.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `ssao.wgsl` :: `vs_main` — vertex. */
export function ssaoVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/ssao.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `ssao.wgsl` :: `fs_main` — fragment. */
export function ssaoFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/ssao.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        1, // samplers
        0, // storage textures
        0, // storage buffers
        2, // uniform buffers
    );
}

/** `ssao_blur.wgsl` :: `vs_main` — vertex. */
export function ssaoBlurVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/ssao_blur.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `ssao_blur.wgsl` :: `fs_main` — fragment. */
export function ssaoBlurFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/ssao_blur.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        1, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `textured.wgsl` :: `vs_main` — vertex. */
export function texturedVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/textured.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        1, // uniform buffers
    );
}

/** `textured.wgsl` :: `fs_main` — fragment. */
export function texturedFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/textured.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        1, // samplers
        0, // storage textures
        0, // storage buffers
        1, // uniform buffers
    );
}

/** `tonemap.wgsl` :: `vs_main` — vertex. */
export function tonemapVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/tonemap.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `tonemap.wgsl` :: `fs_main` — fragment. */
export function tonemapFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/tonemap.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        1, // samplers
        0, // storage textures
        0, // storage buffers
        1, // uniform buffers
    );
}

/** `triangle.wgsl` :: `vs_main` — vertex. */
export function triangleVsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/triangle.vs_main.spv",
        "vs_main",
        SDL_GPUShaderStage.VERTEX,
        0, // samplers
        0, // storage textures
        0, // storage buffers
        0, // uniform buffers
    );
}

/** `triangle.wgsl` :: `fs_main` — fragment. */
export function triangleFsMain(device: Pointer<SDL_GPUDevice>): Pointer<SDL_GPUShader> | null {
    return loadShader(
        device,
        "shaders/out/triangle.fs_main.spv",
        "fs_main",
        SDL_GPUShaderStage.FRAGMENT,
        1, // samplers
        0, // storage textures
        0, // storage buffers
        1, // uniform buffers
    );
}
